### ISSUE TITLE
Clicking a th to sort with that field Toggles the filter dropdown

### ISSUE THREAD

**Issue by BenOussama180** [LowerRockLabs/LaravelLivewireTablesAdvancedFilters#55]
so clicking on a sort button while having NO filters activated will toggle thhe filters dropdown for some reason
![image](https://user-images.githubusercontent.com/81111919/225343625-23c7db90-1097-4cb2-9251-594bb6a71ad9.png)

u can try it in my test repo

**Comment by lrljoe** [comment]
Fix issued, 1.0.10

Once Rappasoft accept some of the pull requests I've submitted, then I can remove a lot of the added code that sets up the filters to remain open when using the DatePicker/SmartSelect.  This should also improve performance further.

At the moment I'm having to modify some of the wrapper/filter elements whenever any of the Advanced Filters are generated, and fix the issues that the default code causes (such as the filters menu closing prematurely)

If the PR doesn't go through then I have an alternative standing by which will clean things up more smoothly as well.
