### ISSUE TITLE
Alpine error on NumberRangeFilter

### ISSUE THREAD

**Issue by dgillier** [LowerRockLabs/LaravelLivewireTablesAdvancedFilters#59]
I added this filter to my table:
```
            NumberRangeFilter::make(__('cruds.group.min_members'),'range')
                ->config([
                    'min' => 0,
                    'max' => 100,
                    'cssInclude' => 'inline,'
                ])
                ->filter(function (Builder $builder, array $numberRange) {
                    $builder->whereHas('users', operator: '>=', count: $numberRange['min'])
                        ->whereHas('users', operator: '<=', count: $numberRange['max']);
                }),
```
And got his error, I'm probably missing  something...

```
alpine.js:115 Alpine Error: "ReferenceError: $refs is not defined"

Expression: "{
    allFilters: $wire.entangle('table.filters'),
     twMenuElements: document.getElementsByClassName('relative block md:inline-block text-left'),         currentMin: $refs.filterMin.value,
    currentMax: $refs.filterMax.value,
    wireValues: $wire.entangle('table.filters.range'),
    defaultMin: 0,
    defaultMax: 100,
    restrictUpdates: true,
    setupFilterMenu() {
        if (document.querySelector('[aria-labelledby="filters-menu"]') !== null) {
            document.querySelector('[aria-labelledby="filters-menu"]').classList.add('md:w-80');
            document.querySelector('[aria-labelledby="filters-menu"]').classList.remove('md:w-56');
        }

        if (document.getElementById('table-filter-range-label') === null) {
            if (document.getElementById('numberRangeContainerrange').parentElement.firstElementChild !== null) {
                document.getElementById('numberRangeContainerrange').parentElement.firstElementChild.classList.add('hidden');
                document.getElementById('numberRangeContainerrange').parentElement.firstElementChild.classList.add('d-none');
            }
        } else {
            document.getElementById('table-filter-range-label').classList.add('hidden');
            document.getElementById('table-filter-range-label').classList.add('d-none');
        }

        if (document.getElementById('table-filter-range-labelInternal') !== null) {
            document.getElementById('table-filter-range-labelInternal').classList.remove('hidden');
            document.getElementById('table-filter-range-labelInternal').classList.remove('d-none');
        }
         for (let i = 0; i < this.twMenuElements.length; i++) {
            if (!this.twMenuElements.item(i).getAttribute('x-data').includes('childElementOpen'))
            {
                this.twMenuElements.item(i).setAttribute('x-data', '{ open: false, childElementOpen: true  }');
                this.twMenuElements.item(i).setAttribute('x-on:mousedown.away', 'if (!childElementOpen) { open = false }');
            }
        }         
    },
    updateStyles() {
        document.getElementById('table.filters.range').style.setProperty('--value-b', $refs.filterMin.value);
        document.getElementById('table.filters.range').style.setProperty('--text-value-b', JSON.stringify($refs.filterMin.value));
        document.getElementById('table.filters.range').style.setProperty('--value-a', $refs.filterMax.value);
        document.getElementById('table.filters.range').style.setProperty('--text-value-a', JSON.stringify($refs.filterMax.value));
    },
    setupWire() {
        if (this.wireValues !== undefined) {
            $refs.filterMin.value = (this.wireValues['min'] !== undefined) ? this.wireValues['min'] : this.defaultMin;
            $refs.filterMax.value = (this.wireValues['max'] !== undefined) ? this.wireValues['max'] : this.defaultMax;
        } else {
            $refs.filterMin.value = this.defaultMin;
            $refs.filterMax.value = this.defaultMax;
        }
        this.updateStyles();
    },
    allowUpdates() {
        this.restrictUpdates = false;
        this.updateWire();
    },
    updateWire() {
        this.updateStyles();

        if (!this.restrictUpdates) {
            if ($refs.filterMin.value != this.defaultMin || $refs.filterMax.value != this.defaultMax) {
                this.wireValues = { 'min': $refs.filterMin.value, 'max': $refs.filterMax.value };
            }
            this.restrictUpdates = true;
        }
    },
    init() {
        this.setupWire();
        this.setupFilterMenu();
        $watch('allFilters', value => this.setupFilterMenu());
        $watch('allFilters', value => this.setupWire());
    },
}"
```
Thanks, Denis

**Comment by lrljoe** [comment]
Should be sorted now in the latest release.  Let me know if you have any issues as most of my stuff runs on Tailwind rather than Bootstrap!

More than happy to make any adjustments you recommend from your experience with Bootstrap :)

**Comment by dgillier** [comment]
Nope, same errors...
 I'm using Tailwind (V2)  btw

**Comment by lrljoe** [comment]
Have you:

1. Included the blades in your tailwind.config.js content section along with the Rappasoft blades?
2. Are you using popover or slidedown for your filter display?

**Comment by dgillier** [comment]
1. Yes
```
        content: [
            './resources/views/**/*.blade.php',
            './vendor/wire-elements/modal/resources/views/*.blade.php',
            './vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php',
            "./storage/framework/views/*.php",
            './safelist.txt'
        ],
```
2. slidedown
3. No

2.8.2 through a CDN

**Comment by dgillier** [comment]
Just installed v3 of alpine, and I don't have error anymore :)

But got two sliders ??
![Screenshot 2023-03-18 at 12 27 45](https://user-images.githubusercontent.com/37960204/226102668-b755bd47-df89-4f6e-a4f5-2650823fa57c.png)

**Comment by lrljoe** [comment]
Ah!  Neither the core Rappasoft product (v2+) nor this really supports alpine 2.x.

Give me a few hours and I'll see if I can get it working properly in 2.x.

Do you have other dependencies on alpinejs 2.x I'm guessing?

**Comment by dgillier** [comment]
No using 3.x is fine with me :)
But having the slider problems as shown on my previous msg...

**Comment by lrljoe** [comment]
Ah!  Neither the core Rappasoft product (v2+) nor this really supports alpine 2.x.

Give me a few hours and I'll see if I can get it working properly in 2.x.

Do you have other dependencies on alpinejs 2.x I'm guessing?

Both this and the core Rappasoft tables depend on the cascading scope that comes with 3.x to do some of the functionality.

I may be able to leverage some other hooks, but it may not be smooth!

**Comment by dgillier** [comment]
No I'm fine using 3.x ;)
Thanks for your proposal :)

Still I'm having the two slider issue as shown previously...

**Comment by lrljoe** [comment]
For two sliders, that happens if the CSS isn't available. Double check that one of the following is true:

'cssInclude' => 'inline' is set in the config file

OR

You're including the following as part of your webpack:
"import '../../vendor/lowerrocklabs/laravel-livewire-tables-advanced-filters/resources/css/numberRange.min.css';"
AND you have 
'cssInclude' => 'none' set in the config file

OR

You've published the public CSS files via
php artisan vendor:publish livewiretablesadvancedfilters-css
And have set 
'cssInclude' => 'include' set in the config file

I typically would recommend the inline approach as it avoids pain when I inevitably release some updated CSS.

**Comment by lrljoe** [comment]
Or it may be as simple as re-running your build/dev commands!

**Comment by dgillier** [comment]
My mistake, I was using:
```
                ->config([
                    'min' => 0,
                    'max' => 100,
                    'cssInclude ' => 'inline,'
                ])
```
instead of :
`               'numberRange.cssInclude ' => 'inline,'`

Works like a charm now :))
Thanks !!!

Only enhancement I can think, is to have a live update of the indicator, so we now what will be the value when we release the cursor.

**Comment by lrljoe** [comment]
Just did a double take on your tailwind, you're missing this package's content, so if you can replace your current
```
        content: [
            './resources/views/**/*.blade.php',
            './vendor/wire-elements/modal/resources/views/*.blade.php',
            './vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php',
            "./storage/framework/views/*.php",
            './safelist.txt'
        ],
```
WIth
```
        content: [
            './resources/views/**/*.blade.php',
            './vendor/wire-elements/modal/resources/views/*.blade.php',
            './vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php',
            './vendor/lowerrocklabs/laravel-livewire-tables-advanced-filters/resources/views/**/*.blade.php',
            "./storage/framework/views/*.php",
            './safelist.txt'
        ],
```
It should all just start working smoothly.

**Comment by lrljoe** [comment]
That's a very sensible idea, I'll put something together probably later today.

**Comment by dgillier** [comment]
Great !!!

Personally I will only use  the update after releasing the cursor version ;)

**Comment by lrljoe** [comment]
> Great !!!
> 
> Personally I will only use the update after releasing the cursor version ;)

If you want to feed back on how this works for you, then it'd be appreciated:
TW2: [https://tabledemo.lowerrocklabs.com/tailwind](https://tabledemo.lowerrocklabs.com/tailwind)
TW3: [https://tabledemo.lowerrocklabs.com/tailwind3](https://tabledemo.lowerrocklabs.com/tailwind3)

**Comment by lrljoe** [comment]
@dgillier  - v1.0.13 now out with this functionality.

**Comment by dgillier** [comment]
Sorry, was not online...

Just installed it, works perfectly !
Many thanks :)

**Comment by lrljoe** [comment]
No worries. If you have any feedback or issues etc just stick an issue on here.

This started out as just a few filters that I needed for my projects, but happy to stick more customisations etc in as people want.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dgillier** [comment]
Look like there is a small touch event problem on mobile (safari and chrome on ios, I don’t know about android).

When I’m releasing one of the handle, a new search is not launch until I touch with my finger somewhere else…

**Comment by lrljoe** [comment]
That's leftover from before I had the progress displaying as otherwise it'd update the query before you were ready.

I'll switch that off later this evening and issue a new version.

**Comment by lrljoe** [comment]
Apologies. This slipped off the radar over last couple of days. 
Just doing some tests then should be ready.

**Comment by lrljoe** [comment]
1.0.14 released with the fix for this.

**Comment by dgillier** [comment]
Thanks a lot !
